name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Nightly to capture latest base image and flexget version
  schedule:
    - cron: "* 21 * * *"

  # Run tests for any PRs.
  pull_request:

  # Allow to trigger manually from github ui
  workflow_dispatch:

jobs:
  dockerhub-registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Flexget version
        id: version
        run: |
          FLEXGET_VERSION=$(curl -s https://pypi.org/pypi/FlexGet/json | docker run -i stedolan/jq -j ".info.version")
          FLEXGET_SHORT_VERSION=${FLEXGET_VERSION%.*}
          FLEXGET_MAJOR_VERSION=${FLEXGET_SHORT_VERSION%.*}

          echo "full=$FLEXGET_VERSION" >> $GITHUB_OUTPUT
          echo "short=$FLEXGET_SHORT_VERSION" >> $GITHUB_OUTPUT
          echo "major=$FLEXGET_MAJOR_VERSION" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            tingvarsson/flexget
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=${{ steps.version.outputs.full }}
            type=raw,value=${{ steps.version.outputs.short }}
            type=raw,value=${{ steps.version.outputs.major }}
            type=sha,format=long,prefix=
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.full }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            FLEXGET_VERSION=${{ steps.version.outputs.full }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
